In [1]:
#library
import numpy as np 

In [2]:
#ways to create array
lst=[1,2,3,4]
type(lst)

list

In [3]:
a=np.array(lst)
a

array([1, 2, 3, 4])

In [4]:
a.shape
#because it is 1D there is nothing after ,


(4,)

In [5]:
#creste multi-D array 
nested_list=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=np.array(nested_list)
b


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
b.shape
#4=rows and 3=columns 

(4, 3)

In [7]:
#we can reshape with array's of above
b.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
b.reshape(1,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [9]:
b.reshape(4,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [10]:
b.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
#numpy is an homogeneous arrangement
#It is very very fast 
#it is the reference implementation of the python language, written in C & Python
#
import numpy as np 
type(np.array(['vbhvh',2,3]))

numpy.ndarray

In [12]:
#Upcasting 

In [13]:
 np.array(['a',2,3, 4.2132])

array(['a', '2', '3', '4.2132'], dtype='<U6')

In [14]:
#datatype complex
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
#Data type consisting of more than one element

In [16]:
x=np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [17]:
#creating an array from sub_classes:
np.mat(np.array([[1,2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [18]:
np.array(np.mat([1,2,3,4]))

array([[1, 2, 3, 4]])

In [19]:
np.mat(np.array([[1,2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [20]:
#another way 
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [21]:
issubclass(np.matrix,np.ndarray)
#matrix is the subclass of array

True

In [22]:
#convert the input to an array


In [23]:
np.array([12,34,5])
type(np.array([12,34,5]))

numpy.ndarray

In [24]:
np.asarray([12,34,5])
type(np.asarray([12,34,5]))

numpy.ndarray

In [25]:
#np.asarray and np.array are same

In [26]:
a=np.array([12,34,5]) #existing array
type(a)

numpy.ndarray

In [27]:
#convert a list into an array
a=[1,2]
type(a)

list

In [28]:
#ndarray subclasses are not passed through
issubclass(np.matrix, np.ndarray)

True

In [29]:
a=np.matrix([1,2])
a


matrix([[1, 2]])

In [30]:
np.asanyarray([1,2]) is a

False

In [31]:
np.asarray(a) is a 

False

In [32]:
np.array(a,copy=True)

array([[1, 2]])

In [33]:
#numpy.fromfunction
#construct an array by executing a function over each coordinate  

In [34]:
np.fromfunction(lambda i,j:i==j,(3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i, j:i*j,(3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [36]:
#create a new 1-D array from an iterable object 

In [37]:
iterable=(x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001A5B7F6C900>

In [38]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
# A new 1-D array initialized from text data in a string

In [40]:
a=np.fromstring('234 234', sep=' ')
a

array([234., 234.])

In [41]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [42]:
# How to create create a record array from a (flat) list of arrays

In [43]:
x1=np.array([1,2,3,4])

In [44]:
x2=np.array(['a','dd','xyz','12'])

In [45]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [46]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [47]:
print(r[1]["a"])

2


In [48]:
x1[1]=34

In [49]:
x1[1]

34