In [1]:
# is v/s ==
#np.array
#np.asarray

In [2]:
#is v/s ==
lst1=['joy1','joy2','joy3']
lst2=['joy1','joy2','joy3']
lst1==lst2 #== just compares the values in the lst's
#when all vaues are matching it will give True otherwise False

True

In [3]:
lst1=['joy1','joy2','joy4']
lst2=['joy1','joy2','joy3']
lst1==lst2

False

In [4]:
lst1=['joy1','joy2','joy3']
lst2=['joy1','joy2','joy3']
lst1 is lst2   #is will give false it will check that the object is present in that memory 

False

In [5]:
lst1=['joy1','joy2','joy3']
lst2=lst1
lst1 is lst2 #now after lst2=lst1 it is present in same memory i.e why now it is True

True

In [6]:
a='maaya'
b='maaya'
a==b

True

In [7]:
a='maaya'
b='maaya'
a is b

True

In [8]:
a=10
b=10
a==b

True

In [9]:
import numpy as np
## Shallow copy v/s deep copy
a=np.array([1,2,3,4])
b=a

In [10]:
b[0]=6

In [11]:
b

array([6, 2, 3, 4])

In [12]:
a
#when b=a and b is changed the a is also changes this is shallow copy

array([6, 2, 3, 4])

In [13]:
## deep copy
# deep copy is also done the same way but with .copy() so that it creats a different memory location

a=np.array([1,2,3,4])
b=a.copy()

In [14]:
b[0]=6

In [15]:
b

array([6, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
#np.array()
#np.asarray()
a=np.array([1,2,3,4])

In [18]:
np.asarray(a) is a  #here it refers to same memory location

True

In [19]:
np.array(a) is a #here it has different memory location

False

In [20]:
#data Types 
my_list=[1,2,3]
import numpy as np 
arr=np.array(my_list)
print('Type/Class of this object:', type(arr))
print('Here is the vector\n------\n', arr)


Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
------
 [1 2 3]


In [21]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print('Type/Class of this object:', type(mat))
print('Here is the matrix\n-------\n', mat,'\n-----') 
print('Dimension of this matrix:', mat.ndim,sep='') #ndim gives the dimensions of the matrix
print('Size of this matrix: ', mat.size,sep='')  #.size gives the size of the matrix 
print('Shape of this matrix: ', mat.shape,sep='') #.shape gives the shape of the matrix 
print('Data type of this matrix: ', mat.dtype,sep='') #dtype gives the data type of the matrix

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
-------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----
Dimension of this matrix:2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [22]:
#inbuilt function arange and Linspace
#arange=returns evenly spaced values within a given interval
#to create an array using arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#In np.linspace=return evenly spaced no over a specified interval
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
#Matrix Creation 
print('Vector of zeroes\n-------------------\n')
print(np.zeros(5))
#np.zeros=returns a new array of given shape & type,filled with zeros

Vector of zeroes
-------------------

[0. 0. 0. 0. 0.]


In [26]:
print('Matrix of zeros\n-----------------\n')
print(np.zeros((3,4))) #notice tuples

Matrix of zeros
-----------------

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
#it will give a diaognal matrix 
print(np.eye((5)))
print(np.eye((3)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
#retstep
np.linspace(2.0,3.0, num=4, retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [30]:
#return number spaced evenlt on a log scale
np.linspace(2.0,3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [31]:
np.logspace(2.0,3.0, num=4, base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [32]:
np.logspace(2.0,3.0, num=4, endpoint=False)
#endpoint=if true stops the last sample otherwise not incuded

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [33]:
#extract a diagonal or construct a diagonal array 
x=np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
#check what is the diagonal array 
print(x.diagonal())
print(np.diag(x))

[ 0  5 10 15]
[ 0  5 10 15]


In [35]:
#check diagonal below the main diagonal of the matrix (lower skew)
np.diag(x,k=-1)

array([ 4,  9, 14])

In [36]:
#upper skew diagonal 
np.diag(x,k=1)

array([ 1,  6, 11])

In [37]:
#print only the diagonal with rest zeros 
np.diag(np.diag(x))
    

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [38]:
#creat a 2D array with the flatterned input as diagonal 
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [39]:
np.diagflat([1,2],1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [40]:
np.diagflat([1,2],-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [41]:
#an array with ones at and below the given diagonal and zeros elsewhere

In [42]:
np.tri(3,5,1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [44]:
np.tri(3,5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [45]:
#to creat lower triangle with different numbers other than 1
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1)

array([[ 1,  2,  0],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
#return upper triangle of an array.
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12],1])

C:\Users\manisha\anaconda3\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


array([[list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9]),
        list([10, 11, 12]), 1],
       [0, list([4, 5, 6]), list([7, 8, 9]), list([10, 11, 12]), 1],
       [0, 0, list([7, 8, 9]), list([10, 11, 12]), 1],
       [0, 0, 0, list([10, 11, 12]), 1],
       [0, 0, 0, 0, 1]], dtype=object)

In [47]:
#Random number generation
np.random.rand(3,4)


array([[0.03640763, 0.58483069, 0.24488512, 0.78008161],
       [0.20487396, 0.228953  , 0.07018823, 0.95032181],
       [0.04343023, 0.56773606, 0.99989243, 0.83041371]])

In [48]:
print("Random number generation(from UNidorm Distribution)")
print(np.random.rand(2,3)) #2 by 3 matrix with random numbers ranging from 2,3


Random number generation(from UNidorm Distribution)
[[0.22480839 0.1094839  0.12905506]
 [0.74774002 0.78212488 0.03855518]]


In [49]:
print('Numbers from Normal distribution with zero mean & standard deviation 1 i.e standard normal')
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean & standard deviation 1 i.e standard normal
[[-0.90470248  0.14894024 -0.53680026]
 [ 0.13617844  0.61267801 -0.79970959]
 [-0.26114592 -0.60932882 -0.49695528]
 [ 1.22654459  0.28485577  0.24579015]]


In [50]:
np.random.randint(1,10)
#it returns the int in lower to higher int values

2

In [51]:
np.random.randint(1,100,30).reshape(5,6)

array([[ 3, 85, 64,  9, 71, 75],
       [79, 56, 17, 36, 71, 18],
       [13, 82, 25, 39, 69, 30],
       [83, 24, 50, 45,  1, 87],
       [47, 34, 82, 15, 26, 64]])

In [52]:
a=np.random.randint(0,100,30)
print(a)
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.sort(a))

[42 71 93 21 12 63 50 67 65 42 21 61 60 93 80 45 76  9 18 64 39  3 99 59
 81 48 20 16  9 42]
48.96666666666667
99
3
[ 3  9  9 12 16 18 20 21 21 39 42 42 42 45 48 50 59 60 61 63 64 65 67 71
 76 80 81 93 93 99]


In [53]:
a=np.random.randint(0,100,30)
print(a)
print(a.max())
print(a.argmax())#this gives the index fof the maxi value
 

[ 7 94 67 12 89 52 34 35 52 84 90 38 16 56 66 88 70 38 59 74 86 60 13  9
 15 66 21 91  2 62]
94
1


In [54]:
#Universal Functions 
a=np.random.randint(0,100,30).reshape(5,6)
a

array([[19, 25, 88, 83, 48, 60],
       [96, 71, 58, 95, 22,  4],
       [32, 15, 48, 71,  5, 62],
       [45, 15, 89, 68, 96, 28],
       [31, 96, 62, 81, 82, 35]])

In [55]:
a*2 #all elements are multiplied by 2

array([[ 38,  50, 176, 166,  96, 120],
       [192, 142, 116, 190,  44,   8],
       [ 64,  30,  96, 142,  10, 124],
       [ 90,  30, 178, 136, 192,  56],
       [ 62, 192, 124, 162, 164,  70]])

In [56]:
#create a 3x3 matrix
from numpy.random import randint as ri
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[8 2 8]
 [3 8 3]
 [3 6 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 7 8]
 [5 7 4]
 [5 7 2]]


In [57]:
mat1*mat2

array([[24, 14, 64],
       [15, 56, 12],
       [15, 42, 10]])

In [58]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)


Multiplication
------------------
 [[ 74 126  88]
 [ 64  98  62]
 [ 64  98  58]]


In [59]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


<ipython-input-59-ea15cab37cb9>:1: RuntimeWarning: divide by zero encountered in true_divide
  print("\nDivision\n------------------\n", mat1/0)


In [60]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[512   8 512]
 [ 27 512  27]
 [ 27 216 125]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[512   8 512]
 [ 27 512  27]
 [ 27 216 125]]


In [61]:
## Broadcasting 
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [62]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [63]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [64]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [65]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [66]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [67]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


In [68]:
### Array Math

In [69]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


1st Matrix of random single-digit numbers

 [[7 9 3]
 [7 8 3]
 [4 1 1]]

2nd Matrix of random single-digit numbers
------------
 [[7 1 3]
 [8 1 4]
 [2 2 4]]


In [70]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


Sq-root of 1st matrix using np
------------------
 [[2.64575131 3.         1.73205081]
 [2.64575131 2.82842712 1.73205081]
 [2.         1.         1.        ]]


In [71]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.09663316e+03 8.10308393e+03 2.00855369e+01]
 [1.09663316e+03 2.98095799e+03 2.00855369e+01]
 [5.45981500e+01 2.71828183e+00 2.71828183e+00]]


In [72]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.95424251 0.47712125]
 [0.84509804 0.90308999 0.47712125]
 [0.60205999 0.         0.        ]]
[[7 9 3]
 [7 8 3]
 [4 1 1]]
[[7 1 3]
 [8 1 4]
 [2 2 4]]


In [73]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 0 0]
 [7 0 3]
 [0 1 1]]


array([[0, 0, 0],
       [7, 0, 3],
       [0, 1, 1]], dtype=int32)

In [74]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)
A = np.linspace(0,12*np.pi,1001)
A



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])