In [1]:
import pandas as pd 
import numpy as np 
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
titanic_train= pd.read_csv('https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv', sep='\t')
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [3]:
titanic_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [4]:
titanic_train.tail(10)

PassengerId  Survived  Pclass  \
146          147         1       3   
147          148         0       3   
148          149         0       2   
149          150         0       2   
150          151         0       2   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                             Name     Sex   Age  SibSp  Parch  \
146  Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0      0      0   
147              Ford, Miss. Robina Maggie "Ruby"  female   9.0      2      2   
148      Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5      0      2   
149             Byles, Rev. Thomas Roussel Davids    male  42.0      0      0   
150                    Bateman, Rev. Robert James    male  51.0      0      0   
151             Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1      0   
152                              Meo, Mr. Alfonzo    male  55.5      0      0   
153               van Billiard, Mr. Austin Blyler    male  40.5      0      2   
154                         Olsen, Mr. Ole Martin    male   NaN      0      0   
155                   Williams, Mr. Charles Duane    male  51.0      0      1   

          Ticket     Fare Cabin Embarked  
146       350043   7.7958   NaN        S  
147   W./C. 6608  34.3750   NaN        S  
148       230080  26.0000    F2        S  
149       244310  13.0000   NaN        S  
150  S.O.P. 1166  12.5250   NaN        S  
151       113776  66.6000    C2        S  
152   A.5. 11206   8.0500   NaN        S  
153     A/5. 851  14.5000   NaN        S  
154    Fa 265302   7.3125   NaN        S  
155     PC 17597  61.3792   NaN        C

In [6]:
titanic_train.dtypes #gives list of all the datatypes 

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
#collect the object datatypes from the dataset 
titanic_train.dtypes=='object'
a=titanic_train.dtypes[titanic_train.dtypes== 'object'].index
a


Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [9]:
titanic_train[a].describe()

Name   Sex  Ticket Cabin Embarked
count                   156   156     156    31      155
unique                  156     2     145    28        3
top     Samaan, Mr. Youssef  male  113803   D26        S
freq                      1   100       2     2      110

In [10]:
# all the columns of the object dtypes are now in one table
titanic_train[titanic_train.dtypes[titanic_train.dtypes=='object'].index]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female   
152                                   Meo, Mr. Alfonzo    male   
153                    van Billiard, Mr. Austin Blyler    male   
154                              Olsen, Mr. Ole Martin    male   
155                        Williams, Mr. Charles Duane    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
151            113776    C2        S  
152        A.5. 11206   NaN        S  
153          A/5. 851   NaN        S  
154         Fa 265302   NaN        S  
155          PC 17597   NaN        C  

[156 rows x 5 columns]

In [11]:
# total description
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [12]:
# all the columns of the integer dtypes are now in one table
titanic_train[titanic_train.dtypes[titanic_train.dtypes=='int64'].index]

PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
151          152         1       1      1      0
152          153         0       3      0      0
153          154         0       3      0      2
154          155         0       3      0      0
155          156         0       1      0      1

[156 rows x 5 columns]

In [13]:
#missing values
#1 Technique
titanic_train.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
151        False     False   False  False  False  False  False  False   False   
152        False     False   False  False  False  False  False  False   False   
153        False     False   False  False  False  False  False  False   False   
154        False     False   False  False  False   True  False  False   False   
155        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
151  False  False     False  
152  False   True     False  
153  False   True     False  
154  False   True     False  
155  False   True     False  

[156 rows x 12 columns]

In [14]:
#2 Technique
titanic_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             30
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          125
Embarked         1
dtype: int64

In [19]:
#3 Technique
titanic_train.isnull().value_counts()

PassengerId  Survived  Pclass  Name   Sex    Age    SibSp  Parch  Ticket  Fare   Cabin  Embarked
False        False     False   False  False  False  False  False  False   False  True   False       98
                                             True   False  False  False   False  True   False       27
                                             False  False  False  False   False  False  False       27
                                             True   False  False  False   False  False  False        3
                                             False  False  False  False   False  False  True         1
dtype: int64

In [20]:
#4 Technique
titanic_train.value_counts()

PassengerId  Survived  Pclass  Name                                                 Sex     Age   SibSp  Parch  Ticket       Fare      Cabin        Embarked
152          1         1       Pears, Mrs. Thomas (Edith Wearne)                    female  22.0  1      0      113776       66.6000   C2           S           1
76           0         3       Moen, Mr. Sigurd Hansen                              male    25.0  0      0      348123       7.6500    F G73        S           1
4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803       53.1000   C123         S           1
7            0         1       McCarthy, Mr. Timothy J                              male    54.0  0      0      17463        51.8625   E46          S           1
11           1         3       Sandstrom, Miss. Marguerite Rut                      female  4.0   1      1      PP 9549      16.7000   G6           S           1
12           1         1       Bo

In [23]:
#check the first 15 sorted name
#names of people from 5 to 10 with 2 values skiped
sorted(titanic_train["Name"][5:10:2])

['Moran, Mr. James',
 'Nasser, Mrs. Nicholas (Adele Achem)',
 'Palsson, Master. Gosta Leonard']

In [24]:
titanic_train["Name"].describe()

count                     156
unique                    156
top       Samaan, Mr. Youssef
freq                        1
Name: Name, dtype: object

In [25]:
titanic_train[['Ticket']][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [26]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [27]:
titanic_train['sudh']='sdffs'
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   sudh  
0      0         A/5 21171   7.2500   NaN        S  sdffs  
1      0          PC 17599  71.2833   C85        C  sdffs  
2      0  STON/O2. 3101282   7.9250   NaN        S  sdffs  
3      0            113803  53.1000  C123        S  sdffs  
4      0            373450   8.0500   NaN        S  sdffs

In [28]:
titanic_train["Pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
151    1
152    3
153    3
154    3
155    1
Name: Pclass, Length: 156, dtype: int64

In [30]:
#above Pclass has unique so to check that how many unique values are there use below
titanic_train["Pclass"].unique()

array([3, 1, 2], dtype=int64)

In [31]:
new_Pclass=pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [32]:
titanic_train["Cabin"].unique() #check unique values of cabin 

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [37]:
#Data preprocessing 
import numpy as np 
char_cabin= titanic_train["Cabin"].astype(str) #converts data to str 
new_Cabin=[cabin[0] for cabin in char_cabin] #take first letter
new_Cabin= pd.Categorical(new_Cabin)
#new_cabin 
new_Cabin

['n', 'C', 'n', 'C', 'n', ..., 'C', 'n', 'n', 'n', 'n']
Length: 156
Categories (8, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'n']

In [35]:
titanic_train['Cabin']= new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   sudh  
0      0         A/5 21171   7.2500     n        S  sdffs  
1      0          PC 17599  71.2833     C        C  sdffs  
2      0  STON/O2. 3101282   7.9250     n        S  sdffs  
3      0            113803  53.1000     C        S  sdffs  
4      0            373450   8.0500     n        S  sdffs

In [38]:
#check null values in age 
titanic_train['Age'].isnull().sum()

30

In [40]:
#to check which all values are missing, here is the list
missing=np.where(titanic_train["Age"].isnull()==True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [42]:
#comparing the max fare present i.e the row index of that price
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88], dtype=int64),)

In [43]:
#to check the maximum fare
max(titanic_train["Fare"])

263.0